"create3DTextLabel", Create3DTextLabel, 6, "fffsif"
"remove3DTextLabel", Remove3DTextLabel, 1, "i"
"count3DTextLabels", GetCount, 0, NULL
"set3DTextLabelText", SetText, 2, "is"
"set3DTextLabelDrawDistance", SetDrawDistance, 2, "if"
"set3DTextLabelColor", SetColor, 2, "ii"
"set3DTextLabelPosition", SetPosition, 4, "ifff"
"set3DTextLabelActive", SetActive, 2, "ib"
 "getCameraPosition", GetPosition, 0, NULL 
 "getCameraRotation", GetRotation, 0, NULL 
 "simpleShake", SimpleShake, 3, "fff"
 "triggerServerEvent", TriggerServerEvent, -1, NULL 
 "bindKey", BindKey, 3, "ssc" 
 "unbindKey", UnbindKey, 2, "ss" 
 "isKeyBound", IsKeyBound, 2, "ss" 
 "setWeather", SetWeather, 1, "s" 
 "getWeather", GetWeather, 0, NULL 
 "toggleHud", ToggleHud, 1, "b" 
 "takeScreenshot", TakeScreenshot, 0, NULL 
 "fadeScreen", FadeScreen, -1, NULL 
 "createHudTimer", CreateHudTimer, -1, NULL 
 "setHudTimerRemainingTime", SetHudTimerRemainingTime, 1, "f" 
 "getHudTimerReminaingTime", GetHudTimerRemainingTime, 0, NULL 
 "startHudTimer", StartHudTimer, 0, NULL 
 "stopHudTimer", StopHudTimer, 0, NULL 
 "isHudTimerRunning", IsHudTimerRunning, 0, NULL 
 "destroyHudTimer", DestroyHudTimer, 0, NULL 
 "openMap", OpenMap, 0, NULL 
 "isMapOpen", IsMapOpen, 0, NULL 
 "setGPSTarget", SetGPSTarget, 2, "ff" 
 "removeGPSTarget", RemoveGPSTarget, 0, NULL 
 "disableTranslocator", DisableTranslocator, 1, "b"
 "getFPS", GetFPS, 0, NULL 
 "getScreenSize", GetScreenSize, 0, NULL 
 "getMousePosition", GetMousePosition, 0, NULL 
 "getScreenFromWorld", WorldToScreen, 3, "fff" 
 "getWorldFromScreen", ScreenToWorld, 3, "fff" 
 "showChat", ShowChat, 1, "b" 
 "isChatVisible", IsChatVisible, 0, NULL 
 "isInputVisible", IsInputVisible, 0, NULL 
 "sendMessage", SendMessage, -1, NULL 
 "dxCreateFont", NewFont, 3, "sib" 
 "dxDrawText", DrawText, -1, NULL 
 "dxDrawRectangle", DrawRectangle, 5, "ffffi" 
 "dxDrawLine", DrawLine, 5, "ffffi" 
 "dxGetTextDimensions", GetTextDimensions, 3, "sfs" 
 "dxLoadTexture", LoadTexture, 1, "s" 
 "dxDrawTexture", DrawTexture, -1, NULL 
 "dxDestroyTexture", DestroyTexture, -1, NULL 
 "isTransferBoxShowing", IsTransferBoxShowing, 0, NULL 
 "showCursor", ShowCursor, 1, "b" 
 "isCursorShowing", IsCursorShowing, 0, NULL 
 "isMainMenuShowing", IsMainMenuShowing, 0, NULL 
 "guiCreateElement", CreateElement, -1, NULL 
 "guiDestroyElement", DestroyElement, 1, "p" 
 "guiSetPosition", GuiSetPosition, -1, NULL 
 "guiGetPosition", GuiGetPosition, -1, NULL 
 "guiSetSize", GuiSetSize, -1, NULL 
 "guiGetSize", GuiGetSize, -1, NULL 
 "guiSetVisible", GuiSetVisible, 2, "pb" 
 "guiIsVisible", GuiIsVisible, 1, "p" 
 "guiSetText", GuiSetText, 2, "ps" 
 "guiGetText", GuiGetText, 1, "p" 
 "guiBringToFront", GuiBringToFront, 1, "p" 
 "guiSendToBack", GuiSendToBack, 1, "p" 
 "guiSetAlpha", GuiSetAlpha, 2, "pf" 
 "guiGetAlpha", GuiGetAlpha, 1, "p" 
 "guiSetAlwaysOnTop", GuiSetAlwaysOnTop, 2, "pb" 
 "guiIsAlwaysOnTop", GuiIsAlwaysOnTop, 1, "p" 
 "guiSetInputMasked", GuiSetInputMasked, 2, "pb" 
 "guiIsInputMasked", GuiIsInputMasked, 1, "p" 
 "guiChangeImage", GuiChangeImage, 2, "ps"
 "guiSetSizable", GuiSetSizable, 2, "pb"
 "guiSetMovable", GuiSetMovable, 2, "pb"
 "getLocalPlayer", GetLocalPlayer, 0, NULL 
 "getPlayerName", GetName, 1, "i" 
 "getPlayerPing", GetPing, 1, "i" 
 "getPlayerColour", GetColour, 1, "i" 
 "isPlayerConnected", IsPlayerConnected, 1, "i" 
 "isPlayerOnScreen", IsOnScreen, 1, "i" 
 "isPlayerSpawned", IsSpawned, 1, "i" 
 "setPlayerPosition", SetPosition, 4, "ifff" 
 "getPlayerPosition", GetPosition, 1, "i" 
 "setPlayerRotation", SetRotation, 4, "ifff" 
 "getPlayerRotation", GetRotation, 1, "i" 
 "setPlayerHealth", SetHealth, 2, "if" 
 "getPlayerHealth", GetHealth, 1, "i" 
 "togglePlayerControls", ToggleControls, 1, "b" 
 "isTogglePlayerControls", IsToggleControls, 0, NULL 
 "isPlayerInVehicle", IsInVehicle, 1, "i" 
 "getPlayerVehicle", GetVehicle, 1, "i" 
 "setPlayerDrunkLevel", SetDrunkLevel, 1, "i"
 "getPlayerDrunkLevel", GetDrunkLevel, 0, NULL
 "resetPlayerDrunkLevel", ResetDrunkLevel, 0, NULL
 "setPlayerWantedLevel", SetWantedLevel, 2, "ii"
 "getPlayerWantedLevel", GetWantedLevel, 0, NULL
 "getPlayerMoveState", GetMoveState, 1, "i" 
"setRenderNametags", SetRenderNametags, 1, "b"
"setRenderHealthbar", SetRenderHealthbar, 1, "b"
 "banPlayer", BanPlayer, 4, "iiis" 
 "banSerial", BanSerial, 4, "siis" 
 "unbanSerial", UnbanSerial, 1, "s" 
 "isSerialBanned", IsSerialBanned, 1, "s" 
 "webRequest", WebRequest, -1, NULL 
 "isPlayerConnected", IsConnected, 1, "i" 
 "isPlayerSpawned", IsSpawned, 1, "i" 
 "getPlayerName", GetName, 1, "i" 
 "getPlayerSerial", GetSerial, 1, "i" 
 "setPlayerPosition", SetPosition, 4, "ifff" 
 "getPlayerPosition", GetPosition, 1, "i" 
 "sendPlayerMessage", OutputMessage, -1, NULL 
 "sendPlayerMessageToAll", OutputMessageToAll, -1, NULL 
 "setPlayerRotation", SetRotation, 4, "ifff" 
 "getPlayerRotation", GetRotation, 1, "i" 
 "setPlayerHealth", SetHealth, 2, "if" 
 "getPlayerHealth", GetHealth, 1, "i" 
 "givePlayerWeapon", GiveWeapon, 3, "iii" 
 "getPlayerWeapon", GetWeapon, 1, "i" 
 "getPlayerWeaponBullet", GetWeaponBullet, 1, "i"
 "removePlayerWeapon", RemoveWeapon, -1, NULL 
 "setPlayerColour", SetColour, 2, "ii" 
 "getPlayerColour", GetColour, 1, "i" 
 "togglePlayerHud", ToggleHud, 2, "ib" 
 "setPlayerMoney", SetMoney, 2, "ii" 
 "givePlayerMoney", GiveMoney, 2, "ii" 
 "takePlayerMoney", TakeMoney, 2, "ii" 
 "togglePlayerControls", ToggleControls, 2, "ib" 
 "kickPlayer", Kick, 1, "i" 
 "playSoundForPlayer", PlaySound, 2, "is" 
 "playSoundForAll", PlaySoundToAll, 1, "s" 
 "stopSoundForPlayer", StopSound, 1, "i" 
 "stopSoundForAll", StopSoundToAll, 0, NULL 
 "getPlayerNetworkStats", GetNetworkStats, 1, "i" 
 "triggerClientEvent", TriggerClientEvent, -1, NULL 
 "setPlayerModel", SetModel, 2, "ii" 
 "getPlayerModel", GetModel, 1, "i" 
 "isPlayerInVehicle", IsInVehicle, 1, "i" 
 "getPlayerVehicle", GetVehicle, 1, "i" 
 "getPlayerPing", GetPing, 1, "i" 
 "getPlayerIP", GetIP, 1, "i" 
 "putPlayerInVehicle", PutInVehicle, 3, "iii" 
 "removePlayerFromVehicle", RemoveFromVehicle, 1, "i" 
 "respawnPlayer", RespawnPlayer, 1, "i" 
 "setPlayerAnimStyle", SetAnimStyle, 3, "iss"
 "setPlayerHandModel", SetHandModel, 3, "iii"
 "setGameModeText", SetGameModeText, 1, "s" 
 "setMapName", SetMapName, 1, "s" 
 "setWeather", SetWeather, 1, "s" 
 "setSummer", SetSummer, 1, "b" 
 "getNetworkStats", GetNetworkStats, 0, NULL 
 "getWhoWas", GetWhoWasList, 0, NULL 
 "clearWhoWas", ClearWhoWas, 0, NULL 
 "getWhoWasCount", GetWhoWasCount, 0, NULL 
 "shutdown", Shutdown, 0, NULL 
 "startResource", StartResource, 1, "s" 
 "stopResource", StopResource, 1, "s" 
 "restartResource", RestartResource, 1, "s" 
 "createVehicle", Create, 7, "iffffff" 
 "destroyVehicle", Destroy, 1, "i" 
 "setVehicleRespawnTime", SetRespawnTime, 2, "ii" 
 "getVehicleRespawnTime", GetRespawnTime, 1, "i" 
 "respawnVehicle", RespawnVehicle, 1, "i" 
 "getDistanceBetweenPoints3D", DistanceBetweenPoints3D, 6, "ffffff" 
 "getDistanceBetweenPoints2D", DistanceBetweenPoints2D, 4, "ffff" 
 "isPointInArea3D", PointInArea3D, 9, "fffffffff" 
 "isPointInArea2D", PointInArea2D, 6, "ffffff" 
 "isPointInCircle3D", PointInCircle3D, 7, "fffffff" 
 "isPointInCircle2D", PointInCircle2D, 5, "fffff" 
 "isPointInTube", PointInTube, 8, "ffffffff" 
 "createBlip", Create, 4, "ffii" 
 "destroyBlip", Destroy, 1, "i" 
 "attachBlipToPlayer", AttachToPlayer, 2, "ii" 
 "attachBlipToVehicle", AttachToVehicle, 2, "ii" 
 "attachBlipToPed", AttachToPed, 2, "ii" 
 "addEventHandler", AddEvent, -1, NULL 
 "callEvent", CallEvent, -1, NULL 
 "removeEventHandler", RemoveEvent, -2, "sc" 
 "addCommandHandler", AddCommand, -1, NULL 
 "md5", md5_string, 1, "s" 
 "md5_file", md5_file, 1, "s" 
 "crc32", crc32, 1, "s" 
 "createPed", CreatePed, 7, "iffffff" 
 "destroyPed", DestroyPed, 1, "i" 
 "setPedName", SetPedName, 2, "is" 
 "getPedName", GetPedName, 1, "i" 
 "showPedName", ShowPedName, 2, "ib" 
 "setPedModel", SetPedModel, 2, "ii" 
 "getPedModel", GetPedModel, 1, "i" 
 "getPedPosition", GetPedPosition, 1, "i" 
 "getPlayerMoney", GetMoney, 1, "i" 
 "getPlayers", GetPlayers, 0, NULL
 "setVehiclePosition", SetPosition, 4, "ifff" 
 "getVehiclePosition", GetPosition, 1, "i" 
 "setVehicleRotation", SetRotation, 4, "ifff" 
 "getVehicleRotation", GetRotation, 1, "i" 
 "setVehicleColour", SetColour, 7, "iiiiiii" 
 "getVehicleColour", GetColour, 1, "i" 
 "setVehiclePlateText", SetPlateText, 2, "is" 
 "getVehiclePlateText", GetPlateText, 1, "i" 
 "repairVehicle", Repair, 1, "i" 
 "setVehicleDirtLevel", SetDirtLevel, 2, "if" 
 "getVehicleDirtLevel", GetDirtLevel, 1, "i" 
 "setVehicleEngineState", SetEngineState, 2, "ib" 
 "getVehicleEngineState", GetEngineState, 1, "i" 
 "explodeVehicle", Explode, 1, "i" 
 "setVehiclePartOpen", SetPartOpen, 3, "iib" 
 "isVehiclePartOpen", IsPartOpen, 2, "ii" 
 "setVehicleSirenState", SetSirenState, 2, "ib" 
 "getVehicleSirenState", GetSirenState, 1, "i" 
 "setVehicleBeaconLightState", SetBeaconLightState, 2, "ib"
 "getVehicleBeaconLightState", GetBeaconLightState, 1, "i"
 "setVehicleHornState", SetHornState, 2, "ib" 
 "getVehicleHornState", GetHornState, 1, "i" 
 "setVehicleWindowOpen", SetWindowOpen, 3, "iib" 
 "isVehicleWindowOpen", IsWindowOpen, 2, "ii" 
 "setVehicleTuningTable", SetTuningTable, 2, "ii" 
 "getVehicleTuningTable", GetTuningTable, 1, "i" 
 "setVehicleWheelTexture", SetWheelTexture, 3, "iii" 
 "getVehicleWheelTexture", GetWheelTexture, 2, "ii" 
 "getVehicleModel", GetModel, 1, "i" 
 "getVehicles", GetVehicles, 0, NULL 
 "setVehicleSpeed", SetSpeed, 4, "ifff" 
 "getVehicleSpeed", GetSpeed, 1, "i" 
 "setVehicleFuel", SetFuel, 2, "if" 
 "getVehicleFuel", GetFuel, 1, "i" 
 "setVehicleLightState", SetLightState, 2, "ib" 
 "getVehicleLightState", GetLightState, 1, "i" 
 "setIndicatorLightState", SetIndicatorLightState, 3, "iib"
 "getIndicatorLightState", GetIndicatorLightState, 2, "ii"
 "setTaxiLightState", SetTaxiLightState, 2, "ib"
 "getTaxiLightState", GetTaxiLightState, 1, "i"
 "getVehicleHandbrake", GetVehicleHandbrake, 1, "i"
 "setVehicleHandbrake", SetVehicleHandbrake, 2, "ib"
 "log", Log, 1, "s" 
 "time", Time, 0, NULL 
 "getTickCount", TickCount, 0, NULL 
 "date", Date, 0, NULL 
 "getPlayerCount", PlayerCount, 0, NULL 
 "getMaxPlayers", MaxPlayers, 0, NULL 
 "getServerName", ServerName, 0, NULL 
 "strRand", StrRand, 1, "i"
 "intConcat", IntConcat, 2, "ii"
 "getDateTime", GetDateTime, 0, NULL
 "getPlayerIdFromName", PlayerIdFromName, 1, "s" 
 "getWeaponNameFromId", WeaponNameFromId, 1, "i" 
 "getWeaponIdFromName", WeaponIdFromName, 1, "s" 
 "toRGBA", ToRGBA, 1, "i" 
 "fromRGB", FromRGB, -1, NULL 
 "clamp", Clamp, 3, "fff" 
