ICON_RED          <- [0 ,  1];
ICON_YELLOW       <- [0 ,  2];
ICON_STAR         <- [0 ,  3];
ICON_CROSS        <- [0 ,  5];
ICON_MIC          <- [0 ,  6];
ICON_MASK         <- [0 ,  7];
ICON_GRAY         <- [0 ,  8];
ICON_CUP          <- [0 ,  9];
ICON_KNUCKLES     <- [0 , 10];
ICON_MAFIA        <- [0 , 11];
ICON_MAP          <- [0 , 12];
ICON_BURGER       <- [1 ,  4];
ICON_CLOTH        <- [2 ,  4];
ICON_BRUSKI       <- [3 ,  4];
ICON_WEAPON       <- [4 ,  4];
ICON_ARMY         <- [5 ,  4];
ICON_HOME         <- [6 ,  4];
ICON_GEAR         <- [7 ,  4];
ICON_FUEL         <- [9 ,  4];
ICON_BAR          <- [11,  4];
ICON_PHONE        <- [12,  4];
ICON_LOCK         <- [13,  4];
ICON_REPAIR       <- [14,  4];
ICON_TARGET       <- [17,  0];
ICON_LOGO_GREEN   <- [21,  0];
ICON_LOGO_YELLOW  <- [22,  0];
ICON_LOGO_RED     <- [23,  0];
ICON_LOGO_PINK    <- [24,  0];
ICON_LOGO_BLACK   <- [25,  0];

ICON_RANGE_FULL   <- 4000.0;
